/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-06-02 07:12:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fundProject;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Bean.*;
import DAO.*;
import dbConnection.*;

public final class ProjectPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1558675377959L));
    _jspx_dependants.put("jar:file:/C:/Users/사공정훈/Desktop/eclipse/workspace(jsp)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebProject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/사공정훈/Desktop/eclipse/workspace(jsp)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebProject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("DAO");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("dbConnection");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("Bean");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fparseNumber_0026_005fvar_005fvalue_005fscope_005fintegerOnly_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fparseNumber_0026_005fvar_005fvalue_005fscope_005fintegerOnly_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fparseNumber_0026_005fvar_005fvalue_005fscope_005fintegerOnly_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      DAO.ProjectDAO ProjectDAO = null;
      ProjectDAO = (DAO.ProjectDAO) _jspx_page_context.getAttribute("ProjectDAO", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (ProjectDAO == null){
        ProjectDAO = new DAO.ProjectDAO();
        _jspx_page_context.setAttribute("ProjectDAO", ProjectDAO, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      Bean.ProjectBean ProjectBean = null;
      ProjectBean = (Bean.ProjectBean) _jspx_page_context.getAttribute("ProjectBean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (ProjectBean == null){
        ProjectBean = new Bean.ProjectBean();
        _jspx_page_context.setAttribute("ProjectBean", ProjectBean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      Bean.PresentBean PresentBean = null;
      PresentBean = (Bean.PresentBean) _jspx_page_context.getAttribute("PresentBean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (PresentBean == null){
        PresentBean = new Bean.PresentBean();
        _jspx_page_context.setAttribute("PresentBean", PresentBean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");

	String pj_idxx = request.getParameter("pj_idx");
	String u_idxx = request.getParameter("u_idx");
	
	session.setAttribute("pj_idx", pj_idxx);
	session.setAttribute("u_idx", u_idxx);

	String pj_idx = (String)session.getAttribute("pj_idx");
	String u_idx = (String)session.getAttribute("u_idx");

	ProjectBean pjbean = ProjectDAO.getProject(pj_idx); // bean set
	
	ArrayList<PresentBean> prlist = ProjectDAO.getPresentList(pj_idx);
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>");
      out.print( pjbean.getPj_title() );
      out.write("</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/boardList.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/ProjectPage.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.12.0.min.js\" ></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function tabSetting() {\r\n");
      out.write("            // 탭 컨텐츠 hide 후 현재 탭메뉴 페이지만 show\r\n");
      out.write("            $('.tapPage').hide();\r\n");
      out.write("            $($('.current').find('a').attr('href')).show();\r\n");
      out.write("        \r\n");
      out.write("            // Tab 메뉴 클릭 이벤트 생성\r\n");
      out.write("            $('li').click(function (event) {\r\n");
      out.write("                var tagName = event.target.tagName; // 현재 선택된 태그네임\r\n");
      out.write("                var selectedLiTag = (tagName.toString() == 'A') ? $(event.target).parent('li') : $(event.target); // A태그일 경우 상위 Li태그 선택, Li태그일 경우 그대로 태그 객체\r\n");
      out.write("                var currentLiTag = $('li[class~=current]'); // 현재 current 클래그를 가진 탭\r\n");
      out.write("                var isCurrent = false;  \r\n");
      out.write("                    \r\n");
      out.write("                // 현재 클릭된 탭이 current를 가졌는지 확인\r\n");
      out.write("                isCurrent = $(selectedLiTag).hasClass('current');\r\n");
      out.write("                    \r\n");
      out.write("                // current를 가지지 않았을 경우만 실행\r\n");
      out.write("                if (!isCurrent) {\r\n");
      out.write("                    $($(currentLiTag).find('a').attr('href')).hide();\r\n");
      out.write("                    $(currentLiTag).removeClass('current');\r\n");
      out.write("        \r\n");
      out.write("                    $(selectedLiTag).addClass('current');\r\n");
      out.write("                    $($(selectedLiTag).find('a').attr('href')).show();\r\n");
      out.write("                }\r\n");
      out.write("        \r\n");
      out.write("                return false;\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        $(function () {\r\n");
      out.write("            // 탭 초기화 및 설정\r\n");
      out.write("            tabSetting();\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"ProjectIntro\">\r\n");
      out.write("            <!-- 프로젝트 소개(상단) -->\r\n");
      out.write("                <div class=\"Container\">\r\n");
      out.write("                    <div class=\"ProjectIntro_Wrapper\">\r\n");
      out.write("                        <div class=\"ProjectIntro_Outline\"> \r\n");
      out.write("                        <!-- 프로젝트 name -->\r\n");
      out.write("                            <div class=\"ProjectIntro_OutlineInner\">\r\n");
      out.write("                                <span class=\"ProjectIntro_ProjectCategory\"> ");
      out.print( pjbean.getPj_category() );
      out.write(" </span>\r\n");
      out.write("                                <h1 class=\"ProjectIntro_Title\"> ");
      out.print( pjbean.getPj_title() );
      out.write(" </h1>\r\n");
      out.write("                                <div class=\"ProjectIntro_Creator\">\r\n");
      out.write("                                    <span class=\"ProjectIntro_Profileimg\"></span>\r\n");
      out.write("                                    <span class=\"ProjectIntro_CreatorName\"> ");
      out.print( pjbean.getLeader_nm() );
      out.write(" </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"ProjectIntro_Main\">\r\n");
      out.write("                        <!-- 프로젝트 메인 img -->\r\n");
      out.write("                            <figure class=\"ProjectIntro_MainCoverImgFigure\">\r\n");
      out.write("                                <img class=\"ProjectIntro_MainCoverImg\" src=\"D:/Bumblbug/Bumblbug/img/ProjectIntro_MainCoverImg.jpg\" alt=\"프로젝트 커버 img\">\r\n");
      out.write("                            </figure>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <aside class=\"ProjectIntro_Sub\">\r\n");
      out.write("                        <!-- 프로젝트 후원 현황 -->\r\n");
      out.write("                            <div class=\"ProjectIntro_FundingStatus\">\r\n");
      out.write("                                <div class=\"ProjectIntro_Matric\">\r\n");
      out.write("                                    <div class=\"ProjectIntro_StatusTitle\"> 모인금액 </div>\r\n");
      out.write("                                    <div class=\"ProjectIntro_StatusValue\">\r\n");
      out.write("                                        ");

                                        	int s_price = Integer.parseInt(pjbean.getPj_f_price());
                                        	String str = String.format("%,d", s_price);
                                        
      out.write("\r\n");
      out.write("                                        ");
      out.print( str );
      out.write("\r\n");
      out.write("                                        <span class=\"ProjectIntro_Small\"> 원 </span>\r\n");
      out.write("                                        <span class=\"ProjectIntro_FundingRate\">\r\n");
      out.write("                                        ");
	
                                        	String cprice = pjbean.getPj_f_price(); // 현재까지 모인 금액
                                        	String gprice = pjbean.getObj_price();	// 목표 금액
                                        
                                        	String goalAmount = ProjectDAO.goalAmount(cprice, gprice);
                                        
      out.write("\r\n");
      out.write("                                        ");
      out.print( goalAmount + '%' );
      out.write("\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"ProjectIntro_Matric\">\r\n");
      out.write("                                    <div class=\"ProjectIntro_StatusTitle\"> 남은시간 </div>\r\n");
      out.write("                                    <div class=\"ProjectIntro_StatusValue\">\r\n");
      out.write("                                        ");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /fundProject/ProjectPage.jsp(129,40) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("now");
        // /fundProject/ProjectPage.jsp(129,40) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setValue(new java.util.Date() );
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    ");
      if (_jspx_meth_fmt_005fparseNumber_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    ");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    ");
      //  fmt:parseDate
      org.apache.taglibs.standard.tag.rt.fmt.ParseDateTag _jspx_th_fmt_005fparseDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.ParseDateTag) _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.ParseDateTag.class);
      boolean _jspx_th_fmt_005fparseDate_005f0_reused = false;
      try {
        _jspx_th_fmt_005fparseDate_005f0.setPageContext(_jspx_page_context);
        _jspx_th_fmt_005fparseDate_005f0.setParent(null);
        // /fundProject/ProjectPage.jsp(134,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fparseDate_005f0.setVar("deadline");
        // /fundProject/ProjectPage.jsp(134,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fparseDate_005f0.setValue(pjbean.getPj_end_dt());
        // /fundProject/ProjectPage.jsp(134,13) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_fmt_005fparseDate_005f0.setPattern("yyyy-MM-dd");
        int _jspx_eval_fmt_005fparseDate_005f0 = _jspx_th_fmt_005fparseDate_005f0.doStartTag();
        if (_jspx_th_fmt_005fparseDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ffmt_005fparseDate_0026_005fvar_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fparseDate_005f0);
        _jspx_th_fmt_005fparseDate_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fparseDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fparseDate_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    ");
      if (_jspx_meth_fmt_005fparseNumber_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${deadlinefull - nowdayfull}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                                        <span class=\"ProjectIntro_Small\"> 일 </span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"ProjectIntro_Matric\">\r\n");
      out.write("                                    <div class=\"ProjectIntro_StatusTitle\"> 후원자 </div>\r\n");
      out.write("                                    <div class=\"ProjectIntro_StatusValue\">\r\n");
      out.write("                                        ");
      out.print(pjbean.getPj_sup_num() );
      out.write("\r\n");
      out.write("                                        <span class=\"ProjectIntro_Small\"> 명 </span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"ProjectIntro_FundingInfo\">\r\n");
      out.write("                                <div class=\"ProjectIntro_InfoInner\">\r\n");
      out.write("                                    <div> 펀딩 진행중 </div>\r\n");
      out.write("                                    <span>\r\n");
      out.write("                                        \t목표 금액인\r\n");
      out.write("                                        \t");

                                        	int g_price = Integer.parseInt(pjbean.getObj_price());
                                        	String g_str = String.format("%,d", g_price);
                                       		
      out.write("\r\n");
      out.write("                                        \t");
      out.print( g_str );
      out.write("원이 모여야만 결제됩니다.<br>\r\n");
      out.write("                                        \t결제는\r\n");
      out.write("\t\t\t\t\t\t\t\t\t        ");
      out.print(pjbean.getPj_end_dt() );
      out.write("\r\n");
      out.write("                                      \t\t에 다함께 진행됩니다.\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"ProjectIntro_ProjectBtn\">\r\n");
      out.write("                                <div class=\"ProjectIntro_BtnInner\">\r\n");
      out.write("                                    <div class=\"ProjectIntro_PrimaryBtn\">\r\n");
      out.write("                                        <button type=\"button\" class=\"Btn\" onclick=\"location.href='RewardsPage.jsp'\"> 프로젝트 밀어주기 </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </aside>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"ContentsNav\">\r\n");
      out.write("            <!-- 프로젝트 상세 페이지 네비 -->\r\n");
      out.write("                <span style=\"font-size: 0px;\"></span>\r\n");
      out.write("                <nav class=\"ContentsNav_Nav\">\r\n");
      out.write("                    <div class=\"ContentsNav_NavInner\">\r\n");
      out.write("                        <ul class=\"ContentsNav_NavLeft\">\r\n");
      out.write("                            <li class=\"tabMenu current\">\r\n");
      out.write("                                <a class=\"ContentsNav_NavItem\" href=\"#tabContent01\"> 스토리 </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"tabMenu\">\r\n");
      out.write("                                <a class=\"ContentsNav_NavItem\" href=\"#tabContent02\"> 커뮤니티 </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"ProjectPage\">\r\n");
      out.write("            <!-- 프로젝트 상세 설명 + 상품 선택 -->\r\n");
      out.write("                <div class=\"Container\">\r\n");
      out.write("                    <dic class=\"ProjectPage_ProjectContents\">\r\n");
      out.write("                        <div class=\"ProjectPage_ContentsMain\">\r\n");
      out.write("                            <div class=\"ProjectPage_MaineInner\">\r\n");
      out.write("                                <div id=\"tabContent01\" class=\"tabPage\">\r\n");
      out.write("                                    <div class=\"Card\">\r\n");
      out.write("                                        <div class=\"StoryCard\">\r\n");
      out.write("                                            <div class=\"StoryContent\">\r\n");
      out.write("                                                <h2>\r\n");
      out.write("                                                    <img src=\"C:\\Users\\gch15\\Desktop\\WebProject\\img\\ProjectPage_Main.jpg\">\r\n");
      out.write("                                                </h2>\r\n");
      out.write("                                                <h2>&nbsp;</h2>\r\n");
      out.write("                                                <h2>\r\n");
      out.write("                                                    <strong> 배꼬비 첫 번째 프로젝트 </strong>\r\n");
      out.write("                                                    <br>\r\n");
      out.write("                                                    <strong> 에그 후라이엔 케찹찹 노트북 파우치 </strong>\r\n");
      out.write("                                                </h2>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"tabContent02\" class=\"tapPage\">\r\n");
      out.write("                                   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "board/boardList.jsp", out, false);
      out.write("     \r\n");
      out.write("                            </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"ProjectPage_ContentsSub\">\r\n");
      out.write("                            <div class=\"ProjectPage_SubInner\">\r\n");
      out.write("                                <div class=\"Rewards\">\r\n");
      out.write("                                    <div class=\"Rewards_Label\">\r\n");
      out.write("                                        \t선택할 수 있는 <b>");
      out.print( prlist.size() );
      out.write("</b>개의 선물이 있습니다.\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"RewardCard_CardWrapper\">\r\n");
      out.write("                                    \t\r\n");
      out.write("                                    \t");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f1_reused = false;
      try {
        _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f1.setParent(null);
        // /fundProject/ProjectPage.jsp(236,37) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setVar("list");
        // /fundProject/ProjectPage.jsp(236,37) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setValue(prlist );
        int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
        if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
        _jspx_th_c_005fset_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </dic>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fparseNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:parseNumber
    org.apache.taglibs.standard.tag.rt.fmt.ParseNumberTag _jspx_th_fmt_005fparseNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.ParseNumberTag) _005fjspx_005ftagPool_005ffmt_005fparseNumber_0026_005fvar_005fvalue_005fscope_005fintegerOnly_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.ParseNumberTag.class);
    boolean _jspx_th_fmt_005fparseNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fparseNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fparseNumber_005f0.setParent(null);
      // /fundProject/ProjectPage.jsp(130,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fparseNumber_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${now.time / (1000*60*60*24)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /fundProject/ProjectPage.jsp(130,13) name = integerOnly type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fparseNumber_005f0.setIntegerOnly(true);
      // /fundProject/ProjectPage.jsp(130,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fparseNumber_005f0.setVar("nowdayfull");
      // /fundProject/ProjectPage.jsp(130,13) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fparseNumber_005f0.setScope("request");
      int _jspx_eval_fmt_005fparseNumber_005f0 = _jspx_th_fmt_005fparseNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fparseNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fparseNumber_0026_005fvar_005fvalue_005fscope_005fintegerOnly_005fnobody.reuse(_jspx_th_fmt_005fparseNumber_005f0);
      _jspx_th_fmt_005fparseNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fparseNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fparseNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /fundProject/ProjectPage.jsp(132,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${now}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /fundProject/ProjectPage.jsp(132,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setVar("nowdate");
      // /fundProject/ProjectPage.jsp(132,13) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fparseNumber_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:parseNumber
    org.apache.taglibs.standard.tag.rt.fmt.ParseNumberTag _jspx_th_fmt_005fparseNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.ParseNumberTag) _005fjspx_005ftagPool_005ffmt_005fparseNumber_0026_005fvar_005fvalue_005fscope_005fintegerOnly_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.ParseNumberTag.class);
    boolean _jspx_th_fmt_005fparseNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fparseNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fparseNumber_005f1.setParent(null);
      // /fundProject/ProjectPage.jsp(137,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fparseNumber_005f1.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${deadline.time / (1000*60*60*24)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /fundProject/ProjectPage.jsp(137,13) name = integerOnly type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fparseNumber_005f1.setIntegerOnly(true);
      // /fundProject/ProjectPage.jsp(137,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fparseNumber_005f1.setVar("deadlinefull");
      // /fundProject/ProjectPage.jsp(137,13) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fparseNumber_005f1.setScope("request");
      int _jspx_eval_fmt_005fparseNumber_005f1 = _jspx_th_fmt_005fparseNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fparseNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fparseNumber_0026_005fvar_005fvalue_005fscope_005fintegerOnly_005fnobody.reuse(_jspx_th_fmt_005fparseNumber_005f1);
      _jspx_th_fmt_005fparseNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fparseNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fparseNumber_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /fundProject/ProjectPage.jsp(237,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("Presentbean");
      // /fundProject/ProjectPage.jsp(237,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/fundProject/ProjectPage.jsp(237,10) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t                                        <div class=\"Card\">\r\n");
            out.write("\t                                            <div class=\"RewardCard_CardInner\">\r\n");
            out.write("\t                                                <div class=\"RewardCard_Header\">\r\n");
            out.write("\t                                                    <span class=\"RewardCard_PledgeAmount\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Presentbean.supmem_cnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("명이 선택</span>\r\n");
            out.write("\t                                                    <span class=\"RewardCard_QuantityLimited\">\r\n");
            out.write("\t                                                        <span class=\"RewardCard_LimitedRewardLabel\">\r\n");
            out.write("\t                                                        ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Presentbean.limit_amount - Presentbean.supmem_cnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("개 남음</span>\r\n");
            out.write("\t                                                    </span>\r\n");
            out.write("\t                                                </div>\r\n");
            out.write("\t                                                <div class=\"RewardCard_Contents\">\r\n");
            out.write("\t                                                    <div class=\"RewardCard_MinPledgeAmount\">\r\n");
            out.write("\t                                                        ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Presentbean.min_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("원 +\r\n");
            out.write("\t                                                    </div>\r\n");
            out.write("\t                                                    <div class=\"RewardCard_Description\">\r\n");
            out.write("\t                                                        ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Presentbean.p_explain}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("\t                                                    </div>\r\n");
            out.write("\t                                                </div>\r\n");
            out.write("\t                                                <div class=\"RewardCard_Items\">\r\n");
            out.write("\t                                                    <li class=\"RewardCard_ItemList\">\r\n");
            out.write("\t                                                        \t선물목록\r\n");
            out.write("\t                                                    </li>\r\n");
            out.write("\t                                                </div>\r\n");
            out.write("\t                                                <div class=\"RewardCard_DeliveryDate\">\r\n");
            out.write("\t                                                    <span> 예상 전달일 <b>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Presentbean.due_dt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</b></span>\r\n");
            out.write("\t                                                </div>\r\n");
            out.write("\t                                                <div class=\"Divider\"></div>\r\n");
            out.write("\t                                                <button class=\"Button\" onclick=\"location.href='RewardsPage.jsp'\">선물 선택하고 밀어주기</button>\r\n");
            out.write("\t                                            </div>\r\n");
            out.write("\t                                        </div>\r\n");
            out.write("                                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
