/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-06-02 06:31:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fundProject;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import DAO.*;
import Bean.*;
import dbConnection.*;

public final class SuccedFundProc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1558675377959L));
    _jspx_dependants.put("jar:file:/C:/Users/사공정훈/Desktop/eclipse/workspace(jsp)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebProject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Users/사공정훈/Desktop/eclipse/workspace(jsp)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebProject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("DAO");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("dbConnection");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("Bean");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      DAO.ProjectDAO ProjectDAO = null;
      ProjectDAO = (DAO.ProjectDAO) _jspx_page_context.getAttribute("ProjectDAO", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (ProjectDAO == null){
        ProjectDAO = new DAO.ProjectDAO();
        _jspx_page_context.setAttribute("ProjectDAO", ProjectDAO, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      Bean.ProjectBean ProjectBean = null;
      ProjectBean = (Bean.ProjectBean) _jspx_page_context.getAttribute("ProjectBean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (ProjectBean == null){
        ProjectBean = new Bean.ProjectBean();
        _jspx_page_context.setAttribute("ProjectBean", ProjectBean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      Bean.PresentBean PresentBean = null;
      synchronized (session) {
        PresentBean = (Bean.PresentBean) _jspx_page_context.getAttribute("PresentBean", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (PresentBean == null){
          PresentBean = new Bean.PresentBean();
          _jspx_page_context.setAttribute("PresentBean", PresentBean, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      Bean.UserBean UserBean = null;
      UserBean = (Bean.UserBean) _jspx_page_context.getAttribute("UserBean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (UserBean == null){
        UserBean = new Bean.UserBean();
        _jspx_page_context.setAttribute("UserBean", UserBean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      Bean.FundBean FundBean = null;
      synchronized (session) {
        FundBean = (Bean.FundBean) _jspx_page_context.getAttribute("FundBean", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (FundBean == null){
          FundBean = new Bean.FundBean();
          _jspx_page_context.setAttribute("FundBean", FundBean, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');
      Bean.DelBean DelBean = null;
      synchronized (session) {
        DelBean = (Bean.DelBean) _jspx_page_context.getAttribute("DelBean", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (DelBean == null){
          DelBean = new Bean.DelBean();
          _jspx_page_context.setAttribute("DelBean", DelBean, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");

	String pj_idx = (String)session.getAttribute("pj_idx"); //프로젝트 인덱스
	String u_idxx = (String)session.getAttribute("u_idx"); //회원 인덱스
	int u_idx = Integer.parseInt(u_idxx);
	
	String d_idx = request.getParameter("d_idx");
	
	if(d_idx==null) {
		// 회원의 새로운 배송지 DEL_TB insert
		String d_ph = request.getParameter("d_ph");
		String d_zipcode = request.getParameter("d_zipcode");
		String d_addr = request.getParameter("d_addr");
		String d_detail_addr = request.getParameter("d_detail_addr");
		String owner_ph = request.getParameter("owner_ph");
		
		DelBean.setD_u_idx(u_idx);
		DelBean.setD_ph(d_ph);
		DelBean.setD_zipcode(d_zipcode);
		DelBean.setD_addr(d_addr);
		DelBean.setD_detail_addr(d_detail_addr);
		
		Boolean delflag = ProjectDAO.insertDel(DelBean);
		int d_idxx = ProjectDAO.setDelidx(DelBean); 
		
		response.sendRedirect("SuccedFundPage.jsp?d_idx="+d_idxx); // 새로 입력한 배송지 idx 전달
	} else {
		
		response.sendRedirect("SuccedFundPage.jsp?d_idx="+d_idx); // 기존 배송지 idx 전달
	}
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
