/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-06-02 05:26:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1558675377959L));
    _jspx_dependants.put("jar:file:/C:/Users/사공정훈/Desktop/eclipse/workspace(jsp)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebProject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");

	String u_idx = (String) session.getAttribute("u_idx");
	String u_img = (String) session.getAttribute("u_img");
	String u_nm = (String) session.getAttribute("u_nm");
	out.println("u_idx: " + u_idx);
	out.println("u_idx: " + u_nm);
	out.println("u_idx: " + u_img);

      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f1_reused = false;
      try {
        _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f1.setParent(null);
        // /Main/Main.jsp(16,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setVar("u_idx");
        // /Main/Main.jsp(16,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setValue(u_idx);
        int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
        if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
        _jspx_th_c_005fset_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatiblee\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("<script src=\"http://code.jquery.com/ui/1.10.3/jquery-ui.js\"></script>\r\n");
      out.write("<link href=\"Main.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\"> \r\n");
      out.write("<script src=\"jquery-1.8.0.min.js\"></script>\r\n");
      out.write("<script src=\"Main.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"header-wrap\">\r\n");
      out.write("\t\t<div class=\"header\">\r\n");
      out.write("\t\t\t<div class=\"hpName-wrap\">\r\n");
      out.write("\t\t\t\t<a class=\"hpName\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Main/Main.jsp\">Bumblebug</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"leftproject-bar\">\r\n");
      out.write("\t\t\t\t<a class=\"view-project\" href=\"../container/tour_main.html\">프로젝트\r\n");
      out.write("\t\t\t\t\t둘러보기</a> <a class=\"view-project\" href=\"http://www.naver.com\">프로젝트\r\n");
      out.write("\t\t\t\t\t올리기</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t");
            if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("\t\t\t\t");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f1_reused = false;
            try {
              _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /Main/Main.jsp(54,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty u_img}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
              if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t\t<div class=\"rightproject-bar\">\r\n");
                  out.write("\t\t\t\t\t\t<button class=\"search\"></button>\r\n");
                  out.write("\t\t\t\t\t\t<span class=\"view-project\" style=\"padding:0 10px;\">");
                  out.print(u_nm);
                  out.write("</span>\r\n");
                  out.write("\t\t\t\t\t\t<a href=\"../Mypage/Mypage_menu.jsp\" class=\"view-login\">  <img\r\n");
                  out.write("\t\t\t\t\t\t\tsrc=\"../UserProfile/");
                  out.print(u_img);
                  out.write("\" alt=\"profile\"\r\n");
                  out.write("\t\t\t\t\t\t\tstyle=\"width: auto; height: 35px;\">\r\n");
                  out.write("\t\t\t\t\t\t</a>\r\n");
                  out.write("\t\t\t\t\t</div>\r\n");
                  out.write("\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
              _jspx_th_c_005fwhen_005f1_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t");
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            boolean _jspx_th_c_005fotherwise_005f0_reused = false;
            try {
              _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t\t<div class=\"rightproject-bar\">\r\n");
                  out.write("\t\t\t\t\t\t<button class=\"search\"></button>\r\n");
                  out.write("\t\t\t\t\t\t<span class=\"view-project\" style=\"padding:0 10px;\">");
                  out.print(u_nm);
                  out.write("</span>\r\n");
                  out.write("\t\t\t\t\t\t<a href=\"../Mypage/Mypage_menu.jsp\" class=\"view-login\">  <img\r\n");
                  out.write("\t\t\t\t\t\t\tsrc=\"../UserProfile/smile.png\" alt=\"profile\"\r\n");
                  out.write("\t\t\t\t\t\t\tstyle=\"width: auto; height: 35px;\">\r\n");
                  out.write("\t\t\t\t\t\t</a>\r\n");
                  out.write("\t\t\t\t\t</div>\r\n");
                  out.write("\t\t\t\t\r\n");
                  out.write("\t\t\t\t\r\n");
                  out.write("\t\t\t\t\r\n");
                  out.write("\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
              _jspx_th_c_005fotherwise_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--//////////////////////////////////////////////////////////////////////////////////-->\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"pr_project\">\r\n");
      out.write("\t\t\t<div class=\"pr\">\r\n");
      out.write("\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t<a href=\"https:www.google.com\"><img src=\"img\\city01.jpg\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"ph \"></a> <a href=\"https:www.google.com\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"img\\city02.jpg\" class=\"ph novisual\"></a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"https:www.google.com\"><img src=\"img\\city03.jpg\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"ph novisual\"></a> <a href=\"https:www.google.com\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"img\\city04.jpg\" class=\"ph novisual\"></a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"https:www.google.com\"><img src=\"img\\city05.jpg\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"ph novisual\"></a> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"..\\container\\img\\main_visual_prev.png\" alt=\"\" class=\"prev\">\r\n");
      out.write("\t\t\t\t\t<img src=\"..\\container\\img\\main_visual_next.png\" alt=\"\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"next\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"control_box\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"cont\"><img src=\"img\\control_on.png\" width=\"40\"\r\n");
      out.write("\t\t\t\t\t\t\talt=\"\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"cont\"><img src=\"img\\control.png\" width=\"40\" alt=\"\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"cont\"><img src=\"img\\control.png\" width=\"40\" alt=\"\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"cont\"><img src=\"img\\control.png\" width=\"40\" alt=\"\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"cont\"><img src=\"img\\control.png\" width=\"40\" alt=\"\"></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- ..........................................................................-->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"recommend_project\">\r\n");
      out.write("\t\t\t<div class=\"recommend_header\">\r\n");
      out.write("\t\t\t\t<a class=\"recommend\" href=\"recommend_page.html\">추천 프로젝트</a>\r\n");
      out.write("\t\t\t\t<button></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"project_card_section\">\r\n");
      out.write("\t\t\t\t<div class=\"project_card_1\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='https:www.google.com'\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"card_1_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"imgbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/city01.jpg\" style=\"width: 200px; height: 150px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>제목</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>게시자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<progress value=\"20\" max=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t</progress>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nowbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"#\">남은기한</a></span> <span style=\"float: right;\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">퍼센트</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"project_card_2\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='https:www.google.com'\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card_2_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"imgbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/city01.jpg\" style=\"width: 200px; height: 150px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>제목</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>게시자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<progress value=\"20\" max=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t</progress>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nowbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"#\">남은기한</a></span> <span style=\"float: right;\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">퍼센트</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"project_card_3\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='https:www.google.com'\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card_3_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"imgbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/city01.jpg\" style=\"width: 200px; height: 150px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>제목</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>게시자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<progress value=\"20\" max=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t</progress>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nowbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"#\">남은기한</a></span> <span style=\"float: right;\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">퍼센트</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"project_card_4\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='https:www.google.com'\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card_4_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"imgbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/city01.jpg\" style=\"width: 200px; height: 150px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>제목</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>게시자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<progress value=\"20\" max=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t</progress>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nowbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"#\">남은기한</a></span> <span style=\"float: right;\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">퍼센트</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- ///////////////////////////////////////////////////////////// -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"planning_project\">\r\n");
      out.write("\t\t\t<div class=\"planning_header\">\r\n");
      out.write("\t\t\t\t<a class=\"recommend\" href=\"recommend_page.html\">추천 프로젝트</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"planning_card_section\">\r\n");
      out.write("\t\t\t\t<div class=\"directbox\">\r\n");
      out.write("\t\t\t\t\t<img src=\"img/main_visual_prev.png\" alt=\"\" class=\"prev\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"planbox1\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"planbox2\"></div>\r\n");
      out.write("\t\t\t\t<div class=\"directbox\">\r\n");
      out.write("\t\t\t\t\t<img src=\"img/main_visual_next.png\" alt=\"\" class=\"next\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"kind_1_project\">\r\n");
      out.write("\t\t\t<div class=\"kind_1_header\">\r\n");
      out.write("\t\t\t\t<a class=\"king_1\" href=\"kind_1_page.html\">카테고리1 프로젝트</a>\r\n");
      out.write("\t\t\t\t<button></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"kind_1_card_section\">\r\n");
      out.write("\t\t\t\t<div class=\"project_card_1\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='https:www.google.com'\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"card_1_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"imgbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/city01.jpg\" style=\"width: 200px; height: 150px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>제목</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>게시자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<progress value=\"20\" max=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t</progress>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nowbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"#\">남은기한</a></span> <span style=\"float: right;\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">퍼센트</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"project_card_2\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='https:www.google.com'\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card_2_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"imgbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/city01.jpg\" style=\"width: 200px; height: 150px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>제목</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>게시자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<progress value=\"20\" max=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t</progress>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nowbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"#\">남은기한</a></span> <span style=\"float: right;\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">퍼센트</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"project_card_3\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='https:www.google.com'\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card_3_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"imgbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/city01.jpg\" style=\"width: 200px; height: 150px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>제목</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>게시자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<progress value=\"20\" max=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t</progress>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nowbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"#\">남은기한</a></span> <span style=\"float: right;\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">퍼센트</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"project_card_4\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='https:www.google.com'\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card_4_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"imgbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/city01.jpg\" style=\"width: 200px; height: 150px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>제목</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>게시자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<progress value=\"20\" max=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t</progress>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nowbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"#\">남은기한</a></span> <span style=\"float: right;\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">퍼센트</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"kind_2_project\">\r\n");
      out.write("\t\t\t<div class=\"kind_2_header\">\r\n");
      out.write("\t\t\t\t<a class=\"kind_2\" href=\"kind_2_page.html\">카테고리1 프로젝트</a>\r\n");
      out.write("\t\t\t\t<button></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"kind_2_card_section\">\r\n");
      out.write("\t\t\t\t<div class=\"project_card_1\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='https:www.google.com'\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"card_1_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"imgbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/city01.jpg\" style=\"width: 200px; height: 150px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>제목</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>게시자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<progress value=\"20\" max=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t</progress>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nowbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"#\">남은기한</a></span> <span style=\"float: right;\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">퍼센트</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"project_card_2\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='https:www.google.com'\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card_2_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"imgbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/city01.jpg\" style=\"width: 200px; height: 150px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>제목</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>게시자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<progress value=\"20\" max=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t</progress>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nowbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"#\">남은기한</a></span> <span style=\"float: right;\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">퍼센트</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"project_card_3\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='https:www.google.com'\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card_3_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"imgbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/city01.jpg\" style=\"width: 200px; height: 150px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>제목</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>게시자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<progress value=\"20\" max=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t</progress>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nowbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"#\">남은기한</a></span> <span style=\"float: right;\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">퍼센트</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"project_card_4\"\r\n");
      out.write("\t\t\t\t\tonclick=\"location.href='https:www.google.com'\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card_4_content\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"imgbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/city01.jpg\" style=\"width: 200px; height: 150px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"textbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>제목</h2>\r\n");
      out.write("\t\t\t\t\t\t\t<h4>게시자</h4>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<progress value=\"20\" max=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t</progress>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"nowbox\">\r\n");
      out.write("\t\t\t\t\t\t\t<span><a href=\"#\">남은기한</a></span> <span style=\"float: right;\"><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\">퍼센트</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--//////////////////////////////////////////////////////////////////////////////////-->\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\t<div class=\"footerSet\">\r\n");
      out.write("\t\t\t<div class=\"foot_1\">\r\n");
      out.write("\t\t\t\t<a class=\"notice\"\r\n");
      out.write("\t\t\t\t\thref=\"C:\\Users\\user\\Desktop\\Project\\footer\\noticePage.html\">공지사항</a><br>\r\n");
      out.write("\t\t\t\t<a class=\"hire\"\r\n");
      out.write("\t\t\t\t\thref=\"C:\\Users\\user\\Desktop\\Project\\footer\\noticePage.html\">채용</a><br>\r\n");
      out.write("\t\t\t\t<a class=\"createGuide\"\r\n");
      out.write("\t\t\t\t\thref=\"C:\\Users\\user\\Desktop\\Project\\footer\\noticePage.html\">창작자가이드</a><br>\r\n");
      out.write("\t\t\t\t<a class=\"settlement\"\r\n");
      out.write("\t\t\t\t\thref=\"C:\\Users\\user\\Desktop\\Project\\footer\\noticePage.html\">결산</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--첫번째 텍스트박스-->\r\n");
      out.write("\t\t\t<div class=\"foot_2\">\r\n");
      out.write("\t\t\t\t<a class=\"termsOfService\"\r\n");
      out.write("\t\t\t\t\thref=\"C:\\Users\\user\\Desktop\\Project\\footer\\noticePage.html\">이용약관</a><br>\r\n");
      out.write("\t\t\t\t<a class=\"privacyPolicy\"\r\n");
      out.write("\t\t\t\t\thref=\"C:\\Users\\user\\Desktop\\Project\\footer\\noticePage.html\">개인정보\r\n");
      out.write("\t\t\t\t\t처리방침</a><br> <a class=\"feePolicy\"\r\n");
      out.write("\t\t\t\t\thref=\"C:\\Users\\user\\Desktop\\Project\\footer\\noticePage.html\">수수료\r\n");
      out.write("\t\t\t\t\t정책</a><br> <a class=\"helpCenter\"\r\n");
      out.write("\t\t\t\t\thref=\"C:\\Users\\user\\Desktop\\Project\\footer\\noticePage.html\">헬프\r\n");
      out.write("\t\t\t\t\t센터</a><br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--두번째 텍스트박스-->\r\n");
      out.write("\t\t\t<div class=\"foot_3\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"javascript:window.open\r\n");
      out.write("                            ('https://www.kakaocorp.com/service/KakaoTalk')\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"./icon/sns_ka.png\" width=\"30\"></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"javascript:window.open\r\n");
      out.write("                            ('https://www.kakaocorp.com/service/KakaoTalk')\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"./icon/sns_face.png\" width=\"30\"></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"javascript:window.open\r\n");
      out.write("                            ('https://www.kakaocorp.com/service/KakaoTalk')\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"./icon/sns_tw.png\" width=\"30\"></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"javascript:window.open\r\n");
      out.write("                            ('https://www.kakaocorp.com/service/KakaoTalk')\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"./icon/sns_insta.png\" width=\"30\"></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"javascript:window.open\r\n");
      out.write("                            ('https://www.kakaocorp.com/service/KakaoTalk')\"><img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"./icon/sns_naver.png\" width=\"30\"></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"location.href='https://www.google.com'\">문의하기</button>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--sns /문의하기 박스-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"foot_4\">\r\n");
      out.write("\t\t\t<span id=\"notice_1\">000은 텀블벅은 플랫폼 제공자로서 프로젝트의 당사자가 아니며, 직접적인\r\n");
      out.write("\t\t\t\t통신판매를 진행하지 않습니다. 프로젝트의 완수 및 선물제공의 책임은 해당 프로젝트의 창작자에게 있으며, 프로젝트와 관련하여\r\n");
      out.write("\t\t\t\t후원자와 발생하는 법적 분쟁에 대한 책임은 해당 창작자가 부담합니다. </span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--세번째텍스트박스-->\r\n");
      out.write("\t\t<div class=\"foot_5\">\r\n");
      out.write("\t\t\t<span id=\"notice_2\"> 텀블벅(주) | 대표 염재승 105-87-52823 | 서울시 강남구\r\n");
      out.write("\t\t\t\t강남대로 364, 12층 1201호 (역삼동) | 통신판매업 2019-서울강남-00797 | 대표전화\r\n");
      out.write("\t\t\t\t02-6080-0760 </span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--네번째 텍스트박스-->\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /Main/Main.jsp(15,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /Main/Main.jsp(15,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/Main/Main.jsp(15,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /Main/Main.jsp(46,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty u_idx}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div class=\"rightproject-bar\">\r\n");
          out.write("\t\t\t\t\t\t<button class=\"search\"></button>\r\n");
          out.write("\t\t\t\t\t\t<a href=\"../Login/login.jsp\" class=\"view-login\">로그인/회원가입</a> \r\n");
          out.write("\t\t\t\t\t\t<img src=\"../UserProfile/smile.png\" alt=\"profile\" style=\"width: auto; height: 35px;\">\r\n");
          out.write("\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }
}
