/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-06-02 07:20:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.fundProject.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import Bean.*;
import DAO.*;
import dbConnection.*;
import java.util.ArrayList;

public final class boardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("DAO");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("dbConnection");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("Bean");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>게시판 목록 보기 페이지</title>\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"board2.css\">-->\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.0.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../../css/boardList.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

	
	request.setCharacterEncoding("UTF-8");
	//int sU_idx = (int)session.getAttribute("sU_idx");
	int sU_idx = 2;

	//String sU_nm = (String)session.getAttribute("u_nm");
	//int sPj_idx = (int)session.getAttribute("sPj_idx");
	
	
      out.write("\r\n");
      out.write("\t<div id=\"test\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"container_community\">\r\n");
      out.write("\t\t<a href=\"board/boardWrite.jsp\">\r\n");
      out.write("\t\t\t<div class=\"upload_msg\">\r\n");
      out.write("\t\t\t<!-- 글쓰기 페이지로 이동 -->\r\n");
      out.write("\t\t\t\t<div class=\"content_container\">\r\n");
      out.write("\t\t\t\t\t<span class=\"profile_img\"></span> 창작자에게 응원 한마디!\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<div class=\"community_button\">\r\n");
      out.write("\t\t\t<div class=\"board_button_container\">\r\n");
      out.write("\t\t\t\t<div class=\"board_button\">모든 게시글</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");

        	CommentDAO commentDAO = new CommentDAO();
        	
        	BoardDAO boardDAO = new BoardDAO();
        	int b_pj_idx = 1;
        	ArrayList<BoardBeans> list = boardDAO.getList(b_pj_idx);
        	//System.out.println(list);
        	for(int i = 0; i< list.size(); i++){
        		String b_nm = boardDAO.getName(Integer.toString(list.get(i).getB_u_idx()));
        		int b_u_idx = list.get(i).getB_u_idx();
        		int b_idx = list.get(i).getB_idx();
        		int c_cnt = commentDAO.getCommentCnt(Integer.toString(b_idx));
        		String b_dt = list.get(i).getB_time().substring(0, 11);
        		String b_content = list.get(i).getB_content();
        		if(b_u_idx == sU_idx){
        			// 자기가 쓴 게시글이 있는경우
        			
      out.write("\r\n");
      out.write("\t\t<!-- 후원한 회원 게시 카드 -->\r\n");
      out.write("\t\t<div class=\"card_board\">\r\n");
      out.write("\t\t\t<div class=\"card_info\">\r\n");
      out.write("\t\t\t\t<!--<div class=\"maker_alert_box\">창작자 업데이트</div>-->\r\n");
      out.write("\t\t\t\t<div class=\"card_wirter_profile\">\r\n");
      out.write("\t\t\t\t\t<span class=\"cd_profile_img\"></span>\r\n");
      out.write("\t\t\t\t\t<div class=\"bd_info\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bd_name\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bd_name_content\">");
      out.print(b_nm );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"bd_reg_dt\">");
      out.print(b_dt );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 글수정 페이지로 이동 -->\r\n");
      out.write("\t\t\t\t\t<a href=\"/Bumblbug/ProjectPageBEdit?b_idx=");
      out.print( b_idx );
      out.write("\"> <img\r\n");
      out.write("\t\t\t\t\t\tclass=\"aaaa\" style=\"width: 30px; height: 30px;\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"board/images/gearIcon.png\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- view 페이지 -->\r\n");
      out.write("\t\t\t<a href=\"../fundProject/ProjectPageBView.jsp?b_idx=");
      out.print(b_idx);
      out.write("&pj_idx=");
      out.print(b_pj_idx);
      out.write("\">\r\n");
      out.write("\t\t\t\t<div class=\"card_content_st\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card_content\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( b_content);
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</a> <a href=\"/Bumblbug/ProjectPageBView.jsp?b_idx=");
      out.print(b_idx);
      out.write("&pj_idx=");
      out.print(b_pj_idx);
      out.write("\">\r\n");
      out.write("\t\t\t\t<div class=\"card_comment_no\">\r\n");
      out.write("\t\t\t\t\t<i class=\"comment_icon\"><img style=\"width: 16px; height: 16px;\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"board/images/kakao.png\"></i>\r\n");
      out.write("\t\t\t\t\t");
      out.print(c_cnt );
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

        		}else{
 						//자신이 쓴 게시글이 없는경우
        		 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 후원한 회원 게시 카드 -->\r\n");
      out.write("\t\t<div class=\"card_board\">\r\n");
      out.write("\t\t\t<div class=\"card_info\">\r\n");
      out.write("\t\t\t\t<!--<div class=\"maker_alert_box\">창작자 업데이트</div>-->\r\n");
      out.write("\t\t\t\t<div class=\"card_wirter_profile\">\r\n");
      out.write("\t\t\t\t\t<span class=\"cd_profile_img\"></span>\r\n");
      out.write("\t\t\t\t\t<div class=\"bd_info\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"bd_name\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bd_name_content\">");
      out.print(b_nm );
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"bd_reg_dt\">");
      out.print(b_dt );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<a href=\"board/boardView.jsp?b_idx=");
      out.print(b_idx );
      out.write("\">\r\n");
      out.write("\t\t\t\t<div class=\"card_content_st\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card_content\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print( b_content );
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</a> <a href=\"board/boardView.jsp?b_idx=");
      out.print(b_idx );
      out.write("\">\r\n");
      out.write("\t\t\t\t<div class=\"card_comment_no\">\r\n");
      out.write("\t\t\t\t\t<i class=\"comment_icon\"><img style=\"width: 16px; height: 16px;\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"board/images/kakao.png\"></i>\r\n");
      out.write("\t\t\t\t\t");
      out.print(c_cnt );
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t");

        	}
       	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
