/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.40
 * Generated at: 2019-06-01 18:49:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import Bean.*;

public final class Mypage_005ffund_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1558675377959L));
    _jspx_dependants.put("jar:file:/C:/Users/사공정훈/Desktop/eclipse/workspace(jsp)/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/WebProject/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("Bean");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      DAO.MypageDAO MypageDAO = null;
      MypageDAO = (DAO.MypageDAO) _jspx_page_context.getAttribute("MypageDAO", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (MypageDAO == null){
        MypageDAO = new DAO.MypageDAO();
        _jspx_page_context.setAttribute("MypageDAO", MypageDAO, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	String u_idx = (String) session.getAttribute("u_idx");
	if (u_idx == null || u_idx.equals("")) {
	response.sendRedirect("../Main/Main.jsp");
	};

	
	String u_img = (String)session.getAttribute("u_img");
	String u_nm = (String)session.getAttribute("u_nm");
	ArrayList<FundBean> list = MypageDAO.getFundBox(u_idx);
	int count = list.size();

      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /Mypage/Mypage_fund.jsp(19,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("count");
        // /Mypage/Mypage_fund.jsp(19,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setValue(count);
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f1_reused = false;
      try {
        _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f1.setParent(null);
        // /Mypage/Mypage_fund.jsp(20,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setVar("u_img");
        // /Mypage/Mypage_fund.jsp(20,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setValue(u_img);
        int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
        if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
        _jspx_th_c_005fset_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>후원현황 :: 텀블벅</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<link href=\"../Main/Main.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container_2 {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tbackground-color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img_box {\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".smile_size {\r\n");
      out.write("\twidth: 160px;\r\n");
      out.write("\theight: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text_setting {\r\n");
      out.write("\tmargin-top: -0.2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".middle_box {\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("\theight: 600px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon_funding_pay_search {\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\theight: 64px;\r\n");
      out.write("\tpadding-bottom: 1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon_funding_pay_all_box {\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\theight: 92%;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon_funding_pay_left {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("\theight: 64px;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon_funding_pay_right {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\twidth: 398px;\r\n");
      out.write("\theight: 64px;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".click_1 {\r\n");
      out.write("\tborder-color: #3a6ff2 !important;\r\n");
      out.write("\tcolor: #3a6ff2 !important;\r\n");
      out.write("\tborder-radius: .28571429rem;\r\n");
      out.write("\tbox-shadow: none;\r\n");
      out.write("\tbackground: rgba(0, 0, 0, .05);\r\n");
      out.write("\talign-self: center;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tpadding: .71428571em .92857143em;\r\n");
      out.write("\tmargin: 0 .35714286em;\r\n");
      out.write("\ttransition: color .1s ease;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tline-height: 1;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\t-webkit-tap-highlight-color: transparent;\r\n");
      out.write("\tflex: 0 0 auto;\r\n");
      out.write("\tuser-select: none;\r\n");
      out.write("\ttext-transform: none;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".click_icon_1 {\r\n");
      out.write("\tbackground: #999;\r\n");
      out.write("\tmargin-left: 1em;\r\n");
      out.write("\tpadding: .3em .71428571em;\r\n");
      out.write("\tbackground-color: #3a6ff2 !important;\r\n");
      out.write("\tborder-color: #3a6ff2 !important;\r\n");
      out.write("\tcolor: #fff !important;\r\n");
      out.write("\tmargin-right: 0;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tline-height: 1;\r\n");
      out.write("\tvertical-align: baseline;\r\n");
      out.write("\ttext-transform: none;\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\tborder: 0 solid transparent;\r\n");
      out.write("\tborder-radius: .28571429rem;\r\n");
      out.write("\ttransition: background .1s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".none_click_2 {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\talign-self: center;\r\n");
      out.write("\tbox-shadow: none;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tpadding: .71428571em .92857143em;\r\n");
      out.write("\tmargin: 0 .35714286em;\r\n");
      out.write("\t/* background: none; */\r\n");
      out.write("\ttransition: color .1s ease;\r\n");
      out.write("\tborder-radius: .28571429rem;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tline-height: 1;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\t-webkit-tap-highlight-color: transparent;\r\n");
      out.write("\tflex: 0 0 auto;\r\n");
      out.write("\tuser-select: none;\r\n");
      out.write("\ttext-transform: none;\r\n");
      out.write("\tcolor: rgba(0, 0, 0, .87);\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".none_icon_2 {\r\n");
      out.write("\tbackground: #999;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tmargin-left: 1em;\r\n");
      out.write("\tpadding: .3em .71428571em;\r\n");
      out.write("\tmargin-right: 0;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tline-height: 1;\r\n");
      out.write("\tvertical-align: baseline;\r\n");
      out.write("\ttext-transform: none;\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\tborder: 0 solid transparent;\r\n");
      out.write("\tborder-radius: .28571429rem;\r\n");
      out.write("\ttransition: background .1s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search_1 {\r\n");
      out.write("\talign-self: center;\r\n");
      out.write("\tbox-shadow: none;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tpadding: .71428571em .92857143em;\r\n");
      out.write("\tmargin: 0px 4.357143em;\r\n");
      out.write("\tbackground: none;\r\n");
      out.write("\ttransition: color .1s ease;\r\n");
      out.write("\tborder-radius: .28571429rem;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tline-height: 1;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\t-webkit-tap-highlight-color: transparent;\r\n");
      out.write("\tflex: 0 0 auto;\r\n");
      out.write("\tuser-select: none;\r\n");
      out.write("\ttext-transform: none;\r\n");
      out.write("\tcolor: rgba(0, 0, 0, .87);\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\tpadding-right: 0 !important;\r\n");
      out.write("\tpadding-left: 0 !important;\r\n");
      out.write("\twidth: 20rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search_2 {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tmargin: -.5em 0;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tfont-size: 1em;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\tfont-style: normal;\r\n");
      out.write("\tdisplay: inline-flex;\r\n");
      out.write("\tcolor: rgba(0, 0, 0, .87);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search_img {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tline-height: 1;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\tright: 0;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth: 2.67142857em;\r\n");
      out.write("\tborder-radius: 0 .28571429rem .28571429rem 0;\r\n");
      out.write("\ttransition: opacity .3s ease;\r\n");
      out.write("\topacity: 1 !important;\r\n");
      out.write("\tfont-size: 1em;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tfont-family: Icons;\r\n");
      out.write("\tfont-style: normal;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\ttext-decoration: inherit;\r\n");
      out.write("\t-webkit-font-smoothing: antialiased;\r\n");
      out.write("\tbackface-visibility: hidden;\r\n");
      out.write("\tbox-sizing: inherit;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".result_funding {\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\theight: 52px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".result_funding_in {\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tmargin-top: 0;\r\n");
      out.write("\tcolor: #545454;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tmin-height: 1em;\r\n");
      out.write("\tbackground: rgba(0, 0, 0, .03);\r\n");
      out.write("\tpadding-left: 25px;\r\n");
      out.write("\tline-height: 1.7em;\r\n");
      out.write("\ttransition: opacity .1s ease, color .1s ease, background .1s ease,\r\n");
      out.write("\t\tbox-shadow .1s ease;\r\n");
      out.write("\tborder-radius: .28571429rem;\r\n");
      out.write("\tbox-shadow: inset 0 0 0 0 rgba(34, 36, 38, .22), 0 0 0 0 transparent;\r\n");
      out.write("\tmargin-bottom: 1em !important;\r\n");
      out.write("\tpadding-top: 10px;\r\n");
      out.write("\tpadding-bottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list_lmg {\r\n");
      out.write("\tmargin-bottom: 0;\r\n");
      out.write("\tmargin-top: 0;\r\n");
      out.write("\tmargin-right: .6em;\r\n");
      out.write("\tfont-size: 1.14285714em;\r\n");
      out.write("\tpadding-bottom: 0;\r\n");
      out.write("\tline-height: 1;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tcolor: #767676 !important;\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\topacity: 1;\r\n");
      out.write("\twidth: 1.18em;\r\n");
      out.write("\theight: 1em;\r\n");
      out.write("\tfont-family: Icons;\r\n");
      out.write("\tfont-style: normal;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\ttext-decoration: inherit;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\t-webkit-font-smoothing: antialiased;\r\n");
      out.write("\tbackface-visibility: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".gift_box {\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\t/* padding-top: 10em;\r\n");
      out.write("            padding-bottom: 10em; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".gift_box_img_text {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\twidth: 891px;\r\n");
      out.write("\theight: 112px;\r\n");
      out.write("\tmargin-left: auto !important;\r\n");
      out.write("\tmargin-right: auto !important;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tmax-width: 100% !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".gift_box_text {\r\n");
      out.write("\topacity: .45;\r\n");
      out.write("\tmargin-bottom: 0;\r\n");
      out.write("\tfont-size: 1.28rem;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tfont-family: SpoqaHanSans, Helvetica Neue, Arial, Helvetica, sans-serif;\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\tline-height: 1.2857em;\r\n");
      out.write("\ttext-transform: none;\r\n");
      out.write("\tcolor: #767676;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".number_chart {\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text_number_div {\r\n");
      out.write("\twidth: 50px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tmargin: 0px 370px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".number_start {\r\n");
      out.write("\tborder-top: none;\r\n");
      out.write("\tpadding-top: .92857143em;\r\n");
      out.write("\tbackground-color: rgba(0, 0, 0, .05);\r\n");
      out.write("\tcolor: rgba(0, 0, 0, .95);\r\n");
      out.write("\tbox-shadow: none;\r\n");
      out.write("\tborder-radius: 0 .28571429rem .28571429rem 0;\r\n");
      out.write("\tmin-width: 3em;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground: rgba(0, 0, 0, .05);\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tline-height: 1;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\t-webkit-tap-highlight-color: transparent;\r\n");
      out.write("\tflex: 0 0 auto;\r\n");
      out.write("\tuser-select: none;\r\n");
      out.write("\tpadding: .92857143em 1.14285714em;\r\n");
      out.write("\ttext-transform: none;\r\n");
      out.write("\ttransition: background .1s ease, box-shadow .1s ease, color .1s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* --------------------------------------------------------------------------------------------------------------------------------- */\r\n");
      out.write(".pj_container {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tmargin-bottom: 1em;\r\n");
      out.write("\tbox-shadow: 0 0 0 0 #d4d4d5, 0 0 0 1px #d4d4d5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pj_container:hover {\r\n");
      out.write("\tbackground: rgba(0, 0, 0, .03);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box_header {\r\n");
      out.write("\tborder-bottom: .5px solid #f4f4f4;\r\n");
      out.write("\tborder-radius: .28571429rem;\r\n");
      out.write("\tfont-size: .9em;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\tpadding-bottom: .5em;\r\n");
      out.write("\tpadding: .5em 1.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box_number {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box_body {\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 1em .7em 1em 1.5em;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box_body_in {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic {\r\n");
      out.write("\tmargin-right: 1em;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmin-width: 150px;\r\n");
      out.write("\tmax-width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_right_text {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fund_ing {\r\n");
      out.write("\tbackground-color: #fff !important;\r\n");
      out.write("\tcolor: #3a6ff2 !important;\r\n");
      out.write("\tborder-color: #3a6ff2 !important;\r\n");
      out.write("\tfont-size: .64285714rem;\r\n");
      out.write("\tbackground: none #fff;\r\n");
      out.write("\tborder: 1px solid rgba(0, 0, 0, .1);\r\n");
      out.write("\tbox-shadow: none;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tline-height: 1;\r\n");
      out.write("\tvertical-align: baseline;\r\n");
      out.write("\tmargin: 0 .14285714em;\r\n");
      out.write("\tpadding: .5833em .833em;\r\n");
      out.write("\ttext-transform: none;\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\tborder-radius: .28571429rem;\r\n");
      out.write("\ttransition: background .1s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fund_end {\r\n");
      out.write("\tbackground-color: #fff !important;\r\n");
      out.write("\tcolor: #f23a62 !important;\r\n");
      out.write("\tborder-color: #f23a62 !important;\r\n");
      out.write("\tfont-size: .64285714rem;\r\n");
      out.write("\tbackground: none #fff;\r\n");
      out.write("\tborder: 1px solid rgba(0, 0, 0, .1);\r\n");
      out.write("\tbox-shadow: none;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tline-height: 1;\r\n");
      out.write("\tvertical-align: baseline;\r\n");
      out.write("\tmargin: 0 .14285714em;\r\n");
      out.write("\tpadding: .5833em .833em;\r\n");
      out.write("\ttext-transform: none;\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\tborder-radius: .28571429rem;\r\n");
      out.write("\ttransition: background .1s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text_1 {\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\tfont-size: 1rem;\r\n");
      out.write("\tpadding-top: .5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text_sm_1 {\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\tfont-size: .65rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text_2 {\r\n");
      out.write("\tfont-size: .85rem;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\tmax-width: 600px;\r\n");
      out.write("\twhite-space: nowrap;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\ttext-overflow: ellipsis;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text_3 {\r\n");
      out.write("\tfont-size: 1rem;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\tpadding-top: .5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".right_here_1 {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pic_right_text::after {\r\n");
      out.write("\tcontent: '';\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 12px;\r\n");
      out.write("\theight: 12px;\r\n");
      out.write("\tmargin: -5px 25px -9px 0px;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\tborder-right: 2px solid black;\r\n");
      out.write("\tborder-top: 2px solid black;\r\n");
      out.write("\ttransform: rotate(45deg);\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 0;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\t/*프로젝트 찾기위한 AJAX 구현 메소드*/\r\n");
      out.write("\tfunction searchProject() {\r\n");
      out.write("\t\tvar input = document.getElementById(\"typing\").value;\r\n");
      out.write("\t\tvar httpRequest = new XMLHttpRequest();\r\n");
      out.write("\t\thttpRequest.onreadystatechange = function() {\r\n");
      out.write("\t\t\tif (httpRequest.readyState == XMLHttpRequest.DONE\r\n");
      out.write("\t\t\t\t\t&& httpRequest.status == 200) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"searchBox\").innerHTML = httpRequest.responseText;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t// POST 방식의 요청은 데이터를 Http 헤더에 포함시켜 전송함.\r\n");
      out.write("\t\thttpRequest.open(\"POST\", \"SearchProjectProc.jsp\", true);\r\n");
      out.write("\t\thttpRequest.setRequestHeader(\"Content-Type\",\r\n");
      out.write("\t\t\t\t\"application/x-www-form-urlencoded\");\r\n");
      out.write("\t\thttpRequest.send(\"search=\" + input); //변수에 데이터 넣으면 post방식\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(function () {\r\n");
      out.write("        $(\".none_click_2\").on(\"click\", function () {\r\n");
      out.write("        \t$(\"#searching\").attr(\"style\",\"display:none;\");\r\n");
      out.write("            if ($(this).hasClass(\"click_1\")) {\r\n");
      out.write("                $(this).removeClass(\"click_1\").children().removeClass(\"click_icon_1\");\r\n");
      out.write("            } else {\r\n");
      out.write("                $(this).addClass(\"click_1\").children().addClass(\"click_icon_1\");\r\n");
      out.write("                $(this).siblings().removeClass(\"click_1\").children().removeClass(\"click_icon_1\");\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if ($(\"#all-fund\").hasClass(\"click_1\")) {\r\n");
      out.write("                $(\"#all\").attr(\"style\", \"display:block;\");\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\"#all\").attr(\"style\", \"display:none;\");\r\n");
      out.write("            }\r\n");
      out.write("            if ($(\"#ing-fund\").hasClass(\"click_1\")) {\r\n");
      out.write("                $(\"#ing\").attr(\"style\", \"display:block;\");\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\"#ing\").attr(\"style\", \"display:none;\");\r\n");
      out.write("            }\r\n");
      out.write("            if ($(\"#ed-fund\").hasClass(\"click_1\")) {\r\n");
      out.write("                $(\"#end\").attr(\"style\", \"display:block;\");\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\"#end\").attr(\"style\", \"display:none;\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("       \r\n");
      out.write("       $(\".searchbox\").on('click', function(){\r\n");
      out.write("        $(\".show-funding\").attr(\"style\", \"display:none;\");\r\n");
      out.write("        $(\"#searching\").attr(\"style\",\"display:block;\");\r\n");
      out.write("        if($(\".none_click_2\").hasClass(\"click_1\")){\r\n");
      out.write("            $(\".none_click_2\").removeClass(\"click_1\").children().removeClass(\"click_icon_1\");;\r\n");
      out.write("        }\r\n");
      out.write("       });\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\t/* --------------------------------------------------------------------------------------------------------------------------------- */\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style=\"overflow: auto;\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../Main/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"img_box\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h3 class=\"text_setting\">");
      out.print(u_nm );
      out.write("님의 후원 현황</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container_2\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"icon_funding_pay_all_box\">\r\n");
      out.write("\t\t\t<div class=\"icon_funding_pay_search\">\r\n");
      out.write("\t\t\t\t<div class=\"icon_funding_pay_left\">\r\n");
      out.write("\t\t\t\t\t<a class=\"none_click_2 click_1\" id=\"all-fund\">모두보기\r\n");
      out.write("\t\t\t\t\t\t<div class=\"none_icon_2 click_icon_1\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t</a> <a class=\"none_click_2\" id=\"ing-fund\">펀딩 진행중\r\n");
      out.write("\t\t\t\t\t\t<div class=\"none_icon_2\">0</div>\r\n");
      out.write("\t\t\t\t\t</a> <a class=\"none_click_2\" id=\"ed-fund\">결제 완료\r\n");
      out.write("\t\t\t\t\t\t<div class=\"none_icon_2\">0</div>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"icon_funding_pay_right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"search_1\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"search_2\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-----------------------------------프로젝트 검색 기능 AJAX --------------------------------------------------------->\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"typing\" class=\"searchbox\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"  프로젝트, 선물, 창작자를 검색하세요\" onkeyup=\"searchProject()\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 100%; height: 35px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<!-----------------------------------프로젝트 검색 기능 AJAX --------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"search_img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"images/search.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 30px; height: 30px; padding: 1px;\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"show-funding\" id=\"all\" style=\"display: block\">\r\n");
      out.write("\t\t\t\t<div class=\"result_funding\">\r\n");
      out.write("\t\t\t\t\t<div class=\"result_funding_in\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"list_lmg\"> <img src=\"images/list.png\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 23px; height: 17px;\">\r\n");
      out.write("\t\t\t\t\t\t</i> 총 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("건의 후원 결과가 있습니다.\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"gift_box\">\r\n");
      out.write("\t\t\t\t\t<!-- -------------------------------프로젝트 박스 include ------------------------------------>\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "MypageProjectbox1.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- -------------------------------프로젝트 박스 include ------------------------------------>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"number_chart\">\r\n");
      out.write("\t\t\t\t\t<div class=\"text_number_div\">\r\n");
      out.write("\t\t\t\t\t\t<numberchart class=\"number_start\">0</numberchart>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- -------------------------------------------------------->\r\n");
      out.write("\t\t\t<div class=\"show-funding\" id=\"ing\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t<div class=\"result_funding\">\r\n");
      out.write("\t\t\t\t\t<div class=\"result_funding_in\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"list_lmg\"> <img src=\"img/list.png\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 23px; height: 17px;\">\r\n");
      out.write("\t\t\t\t\t\t</i> 총 0건의 후원 결과가 있습니다.2\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"gift_box\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"number_chart\">\r\n");
      out.write("\t\t\t\t\t<div class=\"text_number_div\">\r\n");
      out.write("\t\t\t\t\t\t<numberchart class=\"number_start\">1</numberchart>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- -------------------------------------------------------->\r\n");
      out.write("\t\t\t<div class=\"show-funding\" id=\"end\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t<div class=\"result_funding\">\r\n");
      out.write("\t\t\t\t\t<div class=\"result_funding_in\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"list_lmg\"> <img src=\"img/list.png\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 23px; height: 17px;\">\r\n");
      out.write("\t\t\t\t\t\t</i> 총 0건의 후원 결과가 있습니다.3\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"gift_box\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"number_chart\">\r\n");
      out.write("\t\t\t\t\t<div class=\"text_number_div\">\r\n");
      out.write("\t\t\t\t\t\t<numberchart class=\"number_start\">1</numberchart>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- --------------------------------------------------------- -->\r\n");
      out.write("\t\t\t<div class=\"show-funding\" id=\"searching\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t<div class=\"result_funding\">\r\n");
      out.write("\t\t\t\t\t<div class=\"result_funding_in\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"list_lmg\"> <img src=\"img/list.png\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 23px; height: 17px;\">\r\n");
      out.write("\t\t\t\t\t\t</i> 총 0건의 후원 결과가 있습니다.4\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"gift_box\">\r\n");
      out.write("\t\t\t\t\t<div id=\"searchBox\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"number_chart\">\r\n");
      out.write("\t\t\t\t\t<div class=\"text_number_div\">\r\n");
      out.write("\t\t\t\t\t\t<numberchart class=\"number_start\">1</numberchart>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /Mypage/Mypage_fund.jsp(573,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty u_img}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<img src=\"../UserProfile/smile.png\" alt=\"profile\"\r\n");
          out.write("\t\t\t\t\t\tstyle=\"width: auto; height: 80px;\">\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<img src=\"../UserProfile/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${u_img}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"profile\"\r\n");
          out.write("\t\t\t\t\t\tstyle=\"width: auto; height: 80px;\">\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
